openapi: 3.0.0
info:
  title: "Rest API"
  description: "Price Compass REST API"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Product:
      type: "object"
      required:
        - EAN
      properties:
        EAN:
          type: "string"
        name:
          type: "string"
        brand:
          type: "string"
        category:
          type: "string"
        image:
          type: "string"

  parameters:
    EAN:
      name: "EAN"
      description: "Unique product id"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /products:
    get:
      operationId: "products.read_products"
      tags:
        - "Products"
      summary: "Get all products"
      responses:
        "200":
          description: "Successfully read products"
    post:
      operationId: "products.add_product"
      tags:
        - "Products"
      summary: "Add a product"
      requestBody:
        description: "Add product info based on its EAN"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "product EAN"
              type: "object"
              properties:
                EAN:
                  type: "string"
      responses:
        "201":
          description: "Successfully added a product"
  /products/{EAN}:
    get:
      operationId: "products.read_product"
      tags:
        - "Products"
      summary: "Get product information based on its EAN"
      parameters:
        - $ref: "#/components/parameters/EAN"
      responses:
        "200":
          description: "Successfully read product"
